[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["biblioUtils"]

[project]
name = "biblioUtils"
description = "Utility scripts for the management of the bibliography of Philosophie.ch"
version = "2024.0.1"
requires-python = ">=3.11.0"
readme = "README.md"
authors = [
  {name = "Luis Bordo", email = "luis.bordo@philosophie.ch"},
]
maintainers = [
  {name = "Luis Bordo", email = "luis.bordo@philosophie.ch"},
]
dependencies = [
  "titlecase",
  "pydantic",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "mypy",
    "black",
]

[tool.mypy]
python_version = "3.11"
strict = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
    "titlecase",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -s"
testpaths = ["tests"]
pythonpath = ["."]

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''