services:
  dltc-env-ref-pipe:
    image: philosophiech/dltc-env:latest-${ARCH}
    user: "1000:1000"
    container_name: dltc-env-ref-pipe
    tty: true
    stdin_open: true
    hostname: dltc-env-ref-pipe
    volumes:
      - "${DLTC_WORKHOUSE_DIRECTORY}:${CONTAINER_DLTC_WORKHOUSE_DIRECTORY}"
    working_dir: /home/copyeditor/dltc-workhouse
    command: ["LaunchScript", "start"]
