"""
Metadata JSON Parser

Parses metadata JSON strings from CSV files and converts them to the format
expected by DOI update scripts.

Supports two metadata types:
- article: Journal article metadata
- journal_issue: Journal issue metadata

The metadata JSON format is generated by:
- bibliography_to_metadata_json.py (for articles)
- journal_issues_to_metadata_json.py (for journal issues)
"""

import json
import logging
from dataclasses import dataclass
from typing import Dict, Optional, List, Literal, Union
from pydantic import BaseModel, Field, ValidationError

# Set up logger
logger = logging.getLogger(__name__)


@dataclass
class MetadataParsingError:
    """Error information when metadata parsing fails."""

    type: Literal["error", "exception"]
    message: str
    raw_data: str


class ArticleMetadata(BaseModel):
    """Pydantic model for article metadata."""

    type: Literal["article"]
    year: int
    issue: str
    pages: str
    start_page: str
    end_page: str
    volume: str
    journal: str
    license: str
    language: str
    journal_issn: str
    publication_status: str
    keywords: List[str]


class JournalIssueMetadata(BaseModel):
    """Pydantic model for journal issue metadata."""

    type: Literal["journal_issue"]
    issn: str
    volume: str
    issue: str
    year: int
    license: str
    language: str
    keywords: List[str]
    publication_status: str
    title: Optional[str] = None  # Only field that's optional - for special issues


class MetadataJSONParser:
    """Parser for metadata JSON strings using Pydantic models."""

    @staticmethod
    def parse_metadata_json(
        metadata_json_str: str,
    ) -> Union[ArticleMetadata, JournalIssueMetadata, MetadataParsingError]:
        """
        Parse metadata JSON string into a Pydantic model.

        Parameters
        ----------
        metadata_json_str : str
            JSON string containing metadata

        Returns
        -------
        Union[ArticleMetadata, JournalIssueMetadata, MetadataParsingError]
            Parsed metadata model, or MetadataParsingError if parsing fails
        """
        # Check for empty input
        if not metadata_json_str or not metadata_json_str.strip():
            logger.warning("Empty metadata JSON string provided")
            return MetadataParsingError(
                type="error", message="Empty metadata JSON string", raw_data=metadata_json_str or ""
            )

        try:
            data = json.loads(metadata_json_str)
        except json.JSONDecodeError as e:
            logger.error(f"JSON decode error: {e}")
            return MetadataParsingError(
                type="exception", message=f"JSON decode error: {str(e)}", raw_data=metadata_json_str
            )

        # Validate data is a dictionary
        if not isinstance(data, dict):
            logger.error(f"Metadata is not a JSON object (got {type(data).__name__})")
            return MetadataParsingError(
                type="error",
                message=f"Metadata must be a JSON object, got {type(data).__name__}",
                raw_data=metadata_json_str,
            )

        # Determine type and parse with appropriate model
        metadata_type = data.get("type", "")

        if not metadata_type:
            logger.error("Missing 'type' field in metadata JSON")
            return MetadataParsingError(
                type="error", message="Missing required 'type' field in metadata", raw_data=metadata_json_str
            )

        if metadata_type == "article":
            try:
                return ArticleMetadata(**data)
            except ValidationError as e:
                logger.error(f"Article metadata validation error: {e}")
                return MetadataParsingError(
                    type="exception",
                    message=f"Article metadata validation failed: {str(e)}",
                    raw_data=metadata_json_str,
                )
        elif metadata_type == "journal_issue":
            try:
                return JournalIssueMetadata(**data)
            except ValidationError as e:
                logger.error(f"Journal issue metadata validation error: {e}")
                return MetadataParsingError(
                    type="exception",
                    message=f"Journal issue metadata validation failed: {str(e)}",
                    raw_data=metadata_json_str,
                )
        else:
            logger.error(f"Unknown metadata type: {metadata_type}")
            return MetadataParsingError(
                type="error",
                message=f"Unknown metadata type: {metadata_type}. Expected 'article' or 'journal_issue'",
                raw_data=metadata_json_str,
            )

    @staticmethod
    def metadata_to_csv_row(
        metadata: Union[ArticleMetadata, JournalIssueMetadata],
        doi: str,
        link: str,
        update_type: str = "full",
        update_reason: str = "",
        csv_title: str = "",
    ) -> Optional[Dict[str, str]]:
        """
        Convert metadata model to CSV row format for DOI updates.

        Parameters
        ----------
        metadata : Union[ArticleMetadata, JournalIssueMetadata]
            Parsed metadata model
        doi : str
            DOI identifier
        link : str
            Resource URL
        update_type : str
            Update type ("full" or "resource-only")
        update_reason : str
            Reason for the update
        csv_title : str
            Title from CSV (for journal issues, combined with metadata title)

        Returns
        -------
        Optional[Dict[str, str]]
            CSV row dictionary, or None if metadata type is unsupported
        """
        if isinstance(metadata, ArticleMetadata):
            return MetadataJSONParser._article_to_csv_row(metadata, doi, link, update_type, update_reason)
        elif isinstance(metadata, JournalIssueMetadata):
            return MetadataJSONParser._journal_issue_to_csv_row(
                metadata, doi, link, update_type, update_reason, csv_title
            )
        else:
            return None

    @staticmethod
    def _article_to_csv_row(
        metadata: ArticleMetadata, doi: str, link: str, update_type: str, update_reason: str
    ) -> Dict[str, str]:
        """
        Convert article metadata to CSV row format.

        Parameters
        ----------
        metadata : ArticleMetadata
            Article metadata model
        doi : str
            DOI identifier
        link : str
            Resource URL
        update_type : str
            Update type
        update_reason : str
            Update reason

        Returns
        -------
        Dict[str, str]
            CSV row dictionary
        """
        csv_row = {
            "doi": doi,
            "link": link,
            "update_type": update_type,
        }

        if update_reason:
            csv_row["update_reason"] = update_reason

        # Extract article metadata
        csv_row["_year"] = str(metadata.year)
        csv_row["issue"] = metadata.issue
        csv_row["volume"] = metadata.volume
        csv_row["journal_title"] = metadata.journal
        csv_row["language"] = metadata.language
        csv_row["journal_issn"] = metadata.journal_issn

        # Page information
        csv_row["first_page"] = metadata.start_page
        csv_row["last_page"] = metadata.end_page

        # ISSN media type - determine from license or default to electronic
        if metadata.license:
            csv_row["issn_media_type"] = "electronic"
        else:
            csv_row["issn_media_type"] = "print"

        # Publication date media type
        csv_row["publication_date_media_type"] = "online" if metadata.license else "print"

        return csv_row

    @staticmethod
    def _journal_issue_to_csv_row(
        metadata: JournalIssueMetadata, doi: str, link: str, update_type: str, update_reason: str, csv_title: str = ""
    ) -> Dict[str, str]:
        """
        Convert journal issue metadata to CSV row format.

        Parameters
        ----------
        metadata : JournalIssueMetadata
            Journal issue metadata model
        doi : str
            DOI identifier
        link : str
            Resource URL
        update_type : str
            Update type
        update_reason : str
            Update reason
        csv_title : str
            Title from CSV (combined with metadata title if present)

        Returns
        -------
        Dict[str, str]
            CSV row dictionary
        """
        csv_row = {
            "doi": doi,
            "link": link,
            "update_type": update_type,
        }

        if update_reason:
            csv_row["update_reason"] = update_reason

        # Extract journal issue metadata
        csv_row["_year"] = str(metadata.year)
        csv_row["issue"] = metadata.issue
        csv_row["volume"] = metadata.volume
        csv_row["language"] = metadata.language
        csv_row["journal_issn"] = metadata.issn

        # Combine CSV title with metadata title
        # Format: "CSV Title: Metadata Title" if metadata has title, else just "CSV Title"
        if metadata.title and csv_title:
            csv_row["title"] = f"{csv_title}: {metadata.title}"
        elif metadata.title:
            csv_row["title"] = metadata.title
        elif csv_title:
            csv_row["title"] = csv_title
        # If neither exists, leave title empty (journal issues don't require it)

        # Also set issue_title for XML generation (used internally)
        if metadata.title:
            csv_row["issue_title"] = metadata.title

        # ISSN media type - determine from license or default to electronic
        if metadata.license:
            csv_row["issn_media_type"] = "electronic"
        else:
            csv_row["issn_media_type"] = "print"

        # Publication date media type
        csv_row["publication_date_media_type"] = "online" if metadata.license else "print"

        # Add journal title for XML generation
        # Since we don't have journal name in journal_issue metadata, use a default or look it up from ISSN
        # For now, use a default that matches the ISSN
        if csv_row["journal_issn"] == "1746-8361":
            csv_row["journal_title"] = "Dialectica"
        else:
            csv_row["journal_title"] = "Philosophie.ch Publications"

        # Mark this as a journal issue (not an article)
        csv_row["content_type"] = "journal_issue"

        # Add empty author fields - journal issues don't have authors
        # This prevents validation errors that check for author fields
        csv_row["author_given_name"] = ""
        csv_row["author_surname"] = ""

        return csv_row
